apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-amd64
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl-amd64
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: curl-amd64
    spec:
      containers:
      - command:
        - tail
        - -f
        - /dev/null
        image: curlimages/curl
        name: curl
      nodeSelector:
        kubernetes.io/arch: amd64
        kubernetes.io/os: linux